services:
  unit-wp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UNIT_PHP=${UNIT_PHP}
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./unit.config.json:/docker-entrypoint.d/config.json
    networks:
      - proxy
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" #that common network i was talking about
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.sewamobil.tls.certresolver=myresolver"

      # Routers
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure" #configuration inside traefik stack

      # Services
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.scheme=http"

networks:
  proxy:
    external: true
