services:
  unit-wp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./unit.config.json:/docker-entrypoint.d/config.json
    networks:
      - ${TRAEFIK_NETWORK}
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" #that common network i was talking about
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.sewamobil.tls.certresolver=myresolver"

      # Routers
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`, `www.${DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure" #configuration inside traefik stack
        # - "traefik.http.routers.sewamobil.middlewares=strip-path-prefix" # we use this to strip the /service-path/... part off the request so all requests hit / inside our containers (no need to worry about that on the API side)

      # Services
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.scheme=http"

networks:
  ${TRAEFIK_NETWORK}:
    external: true
